# Netlify config: proxy API requests to your deployed Flask API
# Replace https://your-api.example.com with your actual API base URL

[[redirects]]
from = "/predict"
to = "https://krushiai-crop-recommendation.onrender.com/predict"
status = 200
force = true

# If you add more endpoints, you can proxy a path prefix like /api/* instead
# [[redirects]]
# from = "/api/*"
# to = "https://your-api.example.com/:splat"
# status = 200
# force = true
