services:
  - type: web
    name: krushiai-crop-recommendation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://aifarmerassistant-krushiai.netlify.app
